name: Pull Request
on:
  pull_request:
jobs:
  test-semantic-release:
    name: Release dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dry branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        token: ${{ header-token }}
        with:
          branch: 'dry'

      - name: Checkout dry branch
        uses: actions/checkout@v2
        with:
          ref: dry

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Dry run
        token: ${{ header-token }}
        run: unset GITHUB_ACTIONS && npx semantic-release --dry-run --no-ci

      - name: Back to code
        uses: actions/checkout@v3

      - name: Clear dry branch
        uses: dawidd6/action-delete-branch@v3
        with:
          tokoen : ${{ header-token }}
          branches: dry
