name: Preview Release

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  preview_release:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      # Set up Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      # Install dependencies
      - run: npm install
      # Preview the next version
      - run: npm version --dry-run
      # Add a comment to the pull request with the previewed version
      - uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "The next version of this project would be ${{ steps.preview.output }}"
          issue-number: ${{ github.event.number }}
          repo: ${{ github.repository }}
          owner: ${{ github.actor }}
          edit-mode: replace

