name: Preview Version on Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      # Install dependencies
      - run: npm install
      # Preview the next version
      - run: npm version --dry-run
      # Add a comment to the pull request with the previewed version
      - uses: actions/create-or-update-pull-request-comment@v3
        with:
          body: "The next version of this project would be ${{ steps.preview.output }}"
